### PR TITLE
Add module for markduplicates from dragen mapping_metrics files

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/multiqc/7)

### CODE REVIEW

**Comment by woook** [comment]
I'm reviewing

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-:-L2_9xzZtTigIMUZ-XM6:b-bl4ido)*

**Comment by woook** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[multiqc/modules/dragen_markdups/dragen_markdups.py, line 21 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-L2_AnMEN7XSBHnkBpSm:-L2_AnMEN7XSBHnkBpSn:bc6fr7k) ([raw file](https://github.com/moka-guys/multiqc/blob/550bcde8d26508a6bb4459efae11258bcddba583/multiqc/modules/dragen_markdups/dragen_markdups.py#L21)):*
> ```Python
> 		# Initialise the parent object
> 		super(MultiqcModule, self).__init__(name='dragen_markdups', anchor='dragen_markdups',
> 		info="display the % of duplicate reads from dragen ")
> ```

stray space? 
`dragen "`

---

*[multiqc/modules/dragen_markdups/dragen_markdups.py, line 49 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-L2_BIS21Mm3ze1glmJk:-L2_BIS21Mm3ze1glmJl:b2ni1uf) ([raw file](https://github.com/moka-guys/multiqc/blob/550bcde8d26508a6bb4459efae11258bcddba583/multiqc/modules/dragen_markdups/dragen_markdups.py#L49)):*
> ```Python
> 			raise UserWarning
> 
> 		# print number of verifyBAMID reports found and parsed
> ```

eh?

---

*[multiqc/modules/dragen_markdups/dragen_markdups.py, line 60 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-L2_BRt6XOAHA4jE87_i:-L2_BRt6XOAHA4jE87_j:bkqwh0b) ([raw file](https://github.com/moka-guys/multiqc/blob/550bcde8d26508a6bb4459efae11258bcddba583/multiqc/modules/dragen_markdups/dragen_markdups.py#L60)):*
typo
> mapping,etrics.csv

---

*[multiqc/modules/dragen_markdups/dragen_markdups.py, line 75 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-L2_BmfvKTx0W_FL5p7W:-L2_BmfvKTx0W_FL5p7X:bs4dcli) ([raw file](https://github.com/moka-guys/multiqc/blob/550bcde8d26508a6bb4459efae11258bcddba583/multiqc/modules/dragen_markdups/dragen_markdups.py#L75)):*
typo
> thegeneral

extra space
>report """

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/7)*

**Comment by woook** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/7)*

**Comment by woook** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[multiqc/modules/dragen_markdups/dragen_markdups.py, line 60 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-L2_BRt6XOAHA4jE87_i:-L2_Lc2ETSJtGQ2uAtXe:b-met91f) ([raw file](https://github.com/moka-guys/multiqc/blob/550bcde8d26508a6bb4459efae11258bcddba583/multiqc/modules/dragen_markdups/dragen_markdups.py#L60)):*
and 
> key, "

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/7)*

**Comment by aledj2** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[multiqc/modules/dragen_markdups/dragen_markdups.py, line 60 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-L2_BRt6XOAHA4jE87_i:-L2_MDHdN85hqCWIfyQ6:b-896fix) ([raw file](https://github.com/moka-guys/multiqc/blob/550bcde8d26508a6bb4459efae11258bcddba583/multiqc/modules/dragen_markdups/dragen_markdups.py#L60)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

and 
> key, "

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/7)*

**Comment by woook** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/7#-:-L2_ME6x5jwY5VtdhuAL:bnfp4nl)*

**Pull request merged**
