### PR TITLE
For mokaguys

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/multiqc/6)

### CODE REVIEW

**Comment by Graeme-Smith** [comment]
Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[CHANGELOG.md, line 12 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VFqYNP5xR_Cz_-DYx:-L2VFqYNP5xR_Cz_-DYy:b16epgj) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/CHANGELOG.md#L12)):*
> ```Markdown
> 
> * [**VerifyBAMID**](https://genome.sph.umich.edu/wiki/VerifyBamID)
>     * Parses output from VerifyBAMID - a tool to detect contamination in BAM files.
> ```

Pedantic but the creators of the tool capitalize it verifyBamID 

---

*[multiqc/modules/verifybamid/verifybamid.py, line 43 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VSCO9YRoU9XweIJ6n:-L2VSCO9YRoU9XweIJ6o:b-7o528x) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/multiqc/modules/verifybamid/verifybamid.py#L43)):*
> ```Python
>                     self.verifybamid_data[s_name] = parsed_data[s_name]
>         
>         # Filter to strip out ignored sample names
> ```

Expand comment: ", ignored samples are specified by the user in ..."

---

*[multiqc/modules/verifybamid/verifybamid.py, line 136 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VNa59setsuqRl6dmu:-L2VNa59setsuqRl6dmv:b-h32w8c) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/multiqc/modules/verifybamid/verifybamid.py#L136)):*
> ```Python
>         # create empty dictionary
>         data = dict()
>         # for each smaple name and the corresponding dictionary
> ```

Typo - sample

---

*[multiqc/modules/verifybamid/verifybamid.py, line 138 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VUE4a4airiFXg8RJy:-L2VUE4a4airiFXg8RJz:b-96ofnv) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/multiqc/modules/verifybamid/verifybamid.py#L138)):*
> ```Python
>         # for each smaple name and the corresponding dictionary
>         for s_name, d in self.verifybamid_data.items():
>             # create a entry in data dictionary where key is sample namd and value an empty dictionary
> ```

Typo - name

---

*[multiqc/modules/verifybamid/verifybamid.py, line 231 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VUtdPjIxN49JGzFap:-L2VUtdPjIxN49JGzFaq:b-975lbi) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/multiqc/modules/verifybamid/verifybamid.py#L231)):*
> ```Python
>         # if data was found
>         if len(data) > 0:
>             # senf the plot to add section function with data dict and headers
> ```

Typo - Send

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/6)*

**Comment by Graeme-Smith** [comment]
Reviewed 2 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/6)*

**Comment by aledj2** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CHANGELOG.md, line 12 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VFqYNP5xR_Cz_-DYx:-L2VjeW0wsaAJ1yA6EzV:b-896fix) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/CHANGELOG.md#L12)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Pedantic but the creators of the tool capitalize it verifyBamID 
</blockquote></details>

Done.

---

*[multiqc/modules/verifybamid/verifybamid.py, line 43 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VSCO9YRoU9XweIJ6n:-L2VjmJooaveD9bw86Bf:b-896fix) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/multiqc/modules/verifybamid/verifybamid.py#L43)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Expand comment: ", ignored samples are specified by the user in ..."
</blockquote></details>

Done.

---

*[multiqc/modules/verifybamid/verifybamid.py, line 231 at r1](https://reviewable.io:443/reviews/moka-guys/multiqc/6#-L2VUtdPjIxN49JGzFap:-L2Vjvhm11cDK1525pex:b-896fix) ([raw file](https://github.com/moka-guys/multiqc/blob/5ddfe5a536a0e44058d6973f522489c96b3f4eca/multiqc/modules/verifybamid/verifybamid.py#L231)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Typo - Send
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/6)*

**Comment by Graeme-Smith** [comment]
Reviewed 1 of 1 files at r3.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/6)*

**Comment by Graeme-Smith** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/multiqc/6)*

**Pull request merged**
